# import turtle as t
import time

from snake import Snake
from turtle import Screen

screen = Screen()
screen.setup(width = 600, height = 600)
screen.bgcolor("black")
screen.title("Udemy Snake Game")
screen.tracer(False)

# * Snake Object
snake = Snake()


# TODO 1: Create a Snake Body.
# snake_body = []
# snake_length = 3

# ! This code generated by Gemini.
# for i in range(snake_length):
    # snake = t.Turtle()
    # snake.shape("square")
    # snake.color("white")
    # snake.penup()
    # snake.goto(-20 * i, 0)  # Posisi awal setiap segmen
    # snake_body.append(snake)


# TODO 2: Move The Snake.
    # * My Actual Code.
while True:
    screen.update()
    time.sleep(0.5)

    snake.move()

    # ! The code has been changed.
    # for part in snake_body:
        # part.forward(20)
        # screen.update()

    # for part in range(len(snake_body) - 1, 0, -1):
        # the_x = snake_body[part - 1].xcor()
        # the_y = snake_body[part - 1].ycor()
        # snake_body[part].goto(the_x, the_y)

    # snake_body[0].forward(20)


screen.mainloop()
# screen.exitonclick()
