from turtle import Turtle

STARTING_POSITION = [(0, 0), (-20, 0), (-40, 0)]
MOVE_DISTANCE = 20

# TODO 3: Create The Snake Class.
class Snake:

    def __init__(self):
        self.snake_body = []
        self.create_snake()
        pass

    def create_snake(self):
        # ! This code generated by Gemini.
        for position in STARTING_POSITION:
            snake = Turtle()
            snake.shape("square")
            snake.color("white")
            snake.penup()
            snake.goto(position)  # Posisi awal setiap segmen
            self.snake_body.append(snake)

    def move(self):
        for part in range(len(self.snake_body) - 1, 0, -1):
            the_x = self.snake_body[part - 1].xcor()
            the_y = self.snake_body[part - 1].ycor()
            self.snake_body[part].goto(the_x, the_y)

        self.snake_body[0].forward(MOVE_DISTANCE)
